---
efi:
    mountPoint: "/boot"
    recommendedSize: 1GiB
    minimumSize: 512MiB
    label: "CALYPSO-ESP"

userSwapChoices:
    - none

initialPartitioningChoice: none
initialSwapChoice: none

defaultPartitionTableType: gpt
requiredPartitionTableType: gpt
defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4"]

lvm:
    enable: false

allowManualPartitioning: true
essentialMounts: [ "live-*", "control", "ventoy" ]
