---
units:
  - name: "NetworkManager.service"
    action: "enable"
    mandatory: true
  - name: "sddm.service"
    action: "enable"
    mandatory: true
  - name: "power-profiles-daemon.service"
    action: "enable"
  - name: "systemd-resolved.service"
    action: "enable"
  - name: "calypso-wallpapers.service"
    action: "enable"
