---
unpack:
  - source: /run/archiso/bootmnt/arch/x86_64/airootfs.sfs
    sourcefs: squashfs
    destination: ""
    exclude:
      - "etc/calamares/***"
      - "etc/sudoers.d/calypso"
      - "etc/sddm.conf.d/calypso-live.conf"
      - "etc/skel/.config/systemd/user/calypso-live-welcome.service"
      - "usr/bin/calamares"
      - "usr/lib/calamares/***"
      - "usr/share/calamares/***"
      - "usr/share/applications/io.calamares.calamares.desktop"
      - "usr/share/metainfo/io.calamares.calamares.metainfo.xml"
      - "usr/share/icons/***/apps/io.calamares.calamares*"
      - "usr/local/bin/calypso-calamares"
      - "usr/local/bin/calypso-live-welcome"
      - "usr/share/applications/calypso-installer.desktop"
