---
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - lp
    - video
    - network
    - storage
    - name: wheel
      must_exist: false
      system: true
    - audio

sudoersGroup: wheel
autologinGroup: ""

sudoersConfigureWithGroup: false
setRootPassword: false
doReusePassword: false
displayAutologin: true
doAutologin: true

passwordRequirements:
    minLength: 1
    maxLength: 128

user:
  shell: /usr/bin/zsh
  forbidden_names: [ root, nobody, calamares ]
  home_permissions: "o700"

hostname:
  location: EtcFile
  writeHostsFile: true
  forbidden_names: [ localhost ]
