foreground #f4eff8
background #0b0710
cursor #d8b4fe
selection_foreground #0b0710
selection_background #c084fc

color0 #100b16
color1 #f38ba8
color2 #a6e3a1
color3 #f9e2af
color4 #89b4fa
color5 #cba6f7
color6 #94e2d5
color7 #cdd6f4
color8 #585060
color9 #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #cba6f7
color14 #94e2d5
color15 #ffffff
