include ~/.config/kitty/aurora-colors.conf

font_family      JetBrains Mono
font_size        11.0
cursor_shape     beam
cursor_blink_interval 0
shell_integration enabled
confirm_os_window_close 0

background_opacity 0.94
dynamic_background_opacity yes
window_padding_width 14
single_window_padding_width 14
hide_window_decorations yes
remember_window_size no

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
active_tab_font_style bold
inactive_tab_font_style normal

allow_remote_control no
enable_audio_bell no
visual_bell_duration 0.0
bell_on_tab yes
