-- Generated by matugen. Do not edit manually.
return {
  primary = "{{colors.primary.dark.hex}}",
  primary_container = "{{colors.primary_container.dark.hex}}",
  secondary = "{{colors.secondary.dark.hex}}",
  background = "{{colors.background.dark.hex}}",
  surface = "{{colors.surface.dark.hex}}",
  surface_variant = "{{colors.surface_variant.dark.hex}}",
  on_background = "{{colors.on_background.dark.hex}}",
  on_surface = "{{colors.on_surface.dark.hex}}",
  outline = "{{colors.outline.dark.hex}}",
}
